# Generated by Django 4.0.4 on 2022-06-09 21:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Autor')),
                ('slug', models.CharField(max_length=40, unique=True, verbose_name='Slug')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images')),
                ('biografia', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la Categoría')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa/Inactiva')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Tema')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa/Inactiva')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del Usuario')),
                ('apellido', models.CharField(max_length=30, unique=True, verbose_name='Apellido del Usuario')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título del Post')),
                ('slug', models.CharField(max_length=40, unique=True, verbose_name='Slug')),
                ('resumen', models.CharField(max_length=100, unique=True, verbose_name='Resumen del Post')),
                ('imagen', models.ImageField(upload_to='images')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título del Post')),
                ('slug', models.CharField(max_length=40, unique=True, verbose_name='Slug')),
                ('resumen', models.CharField(max_length=100, unique=True, verbose_name='Resumen del Post')),
                ('imagen', models.ImageField(upload_to='images')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.usuario')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.usuario'),
        ),
    ]
