# Generated by Django 4.0.4 on 2022-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='slug',
            field=models.SlugField(max_length=40, unique=True, verbose_name='Slug'),
        ),
    ]
