# Generated by Django 4.0.4 on 2022-06-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_autor_slug_alter_post_slug_alter_resena_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='resumen',
            field=models.TextField(max_length=200, unique=True, verbose_name='Resumen del Post'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='titulo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Título del Libro'),
        ),
    ]
