# Generated by Django 4.0.4 on 2022-06-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_resena_resumen_alter_resena_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Remitente')),
                ('email', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Sugerencia'], [2, 'Reclamo'], [3, 'Otro']], unique=True, verbose_name='Asunto')),
                ('asunto', models.CharField(max_length=50, unique=True, verbose_name='Asunto del Mensaje')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'verbose_name': 'Resena', 'verbose_name_plural': 'Resenas'},
        ),
        migrations.AlterField(
            model_name='resena',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
