# Generated by Django 4.0.4 on 2022-06-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_contacto_alter_resena_options_alter_resena_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
