# Generated by Django 4.0.4 on 2022-06-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
