# Generated by Django 4.0.4 on 2022-06-22 01:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0013_alter_comentario_options_alter_comentario_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=ckeditor.fields.RichTextField(verbose_name='Mensaje'),
        ),
    ]
