# Generated by Django 4.0.4 on 2022-06-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0014_alter_comentario_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='resena',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libros.resena'),
        ),
    ]
