# Generated by Django 4.0.4 on 2022-06-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0016_alter_comentario_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
