# Generated by Django 4.0.4 on 2022-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0018_alter_autor_slug_alter_post_slug_alter_resena_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(upload_to='images'),
        ),
    ]
